### ISSUE TITLE
Non editable input text

### ISSUE THREAD

**Issue by TrianguloY** [TrianguloY/UrlChecker#100]
The input text module is a big edittext. With all the new modules functionalities it is less necessary now to manually edit it. It is bigger than others so reducing it to just a textview could help with the clutter.
I can think of two solutions:

1) A setting to make it "editable" (enabled by default). When enabled it is just as it is now. When disabled instead of a text editor it shows the url as a normal textview (like the log module but with normal font).

2) Replace the editor with the text view as explained above, but add a "pencil" button that when clicked will go back to the current full edittext.

In not sure which one is better, will probably try both and check. (Or maybe use both with a three-option setting)

**Comment by Ilithy** [comment]
>Replace the editor with the text view as explained above, but add a "pencil" button that when clicked will go back to the current full edittext.

>In not sure which one is better, will probably try both and check. (Or maybe use both with a three-option setting)


I find this idea pleasant, it avoids mishandling (touching the text does not open the editor) but still makes it easy to make changes.

and indeed an option so that the behavior of this module is identical to now, for those who prefer the old method will complete this perfectly.
A final option could be simply an unmodifiable display of the input text (really useful?)

**Comment by Ilithy** [comment]
I don't know if it will be implementable as an option for this module (Imput text), but it would be really useful (I think) to have 
- An option to control the text size _(of the url)_
- An option to control the text alignment _(same)_

**Comment by mariachrisochoou** [comment]
Hi! I am interested in this issue and I believe I can help. 
Can I be assigned to this issue? 
I am a first-time contributor, so any help or guidance will be very much appreciated. 

Thank you so much in advance.

**Comment by TrianguloY** [comment]
> Hi! I am interested in this issue and I believe I can help. 
> Can I be assigned to this issue? 
> I am a first-time contributor, so any help or guidance will be very much appreciated. 
> 
> Thank you so much in advance.

Sure! 
The reason I haven't started this yet is that I'm not so sure if it is a good idea, or how to properly implement it. Using a dedicated button to switch from the view-only to the edit-text forms may clutter the screen, perhaps just letting the view-only text view act as a button is enough. It was mentioned that a button will avoid opening the keyboard if you press the input by mistake, but...I prefer to avoid having another extra icon.

So, I think as a first implementation just to have a non-editable textview (probably with smaller font) that when clicked will "convert" to the edit text is a good start.

I don't know what your knowledge of android development is, but feel free to ask for help and I'll try to assist whenever possible. My recommendation is:
- first try to "play" a bit with the app on Android studio to see how the code is structured and feel comfortable. It is splitted into modules so try to find the one responsible for the input text.
- next replace it with a textview (the non-editable version) and try to adjust the style so that it is both clear to see and matches the rest of the app style (or rather lack of style). Post screenshots so I can assist at this step. Remember to keep it updated if the url changes! 
- then make it so that clicking this textview switches to the original edittext. Not sure if it would be a good idea to have both and just toggle the visibility or replace it on the spot, you'll need to check which one is easier...probably the visibility. Switching back from the edittext to the textview is not needed for now, if the user edits the input let's assume it wants to keep editing it (or you can switch back if the url changes from another module, there is a way to do this, the javadocs should help).
- if completed, the last step is to add a toggle in the module settings to choose the default state (and maybe even disable it, for example a selectable with "Always non editable", "Non editable by default", "Editable by default", "Always editable".

- extra points if you also allow changing the size/style of the texts, but for this please ask first just in case.

In general, this could be a very easy and short feature (no more than maybe 5 files, although I can be wrong) so feel free to experiment if you want. Just remember to keep the changes small, and adapt to the existing coding style if possible.

If you need help in the process I'll try to answer them, but please understand if in don't do it right away.

And finally, and this is important, if at any moment you prefer to leave and don't implement this, don't worry! But please say it so I can "release" this issue for others.
