### ISSUE TITLE
make "Ignore the referrer app" deactivatable

### ISSUE THREAD

**Issue by Ilithy** [TrianguloY/UrlChecker#134]
**Is your feature request related to a problem? Please describe.**

The problem I'm having with this (the fact that URLCheck ignores the referring app) makes using URLCheck as a "firewall application" less convenient _(for me at least)_.

I happen to want from my internet browser to use URLcheck to check the link, clean it or whatever, unfortunately, if I want to open it in my browser, currently I have to share it (via URLCheck's share button), then reselect URLCheck, so that it offers me my web browser, it's uncomfortable.

**Describe the solution you'd like**

**If possible**, add an option: (which can be enabled by default) **Ignore the referrer app** _(probably to be put in the opening options)_
This will allow users like me to deactivate it, and find the old behavior of URLCheck ❤️

to illustrate my point, I search for something on google:

![Screenshot_20221026-150203](https://user-images.githubusercontent.com/36798218/198033486-4b36e2b9-2112-4b8b-9c89-c8e92e1c8965.png)

I clean the link

![Screenshot_20221026-150249](https://user-images.githubusercontent.com/36798218/198034208-26ffae31-d26c-41fc-976e-e894881c291a.png)

then I "convert" it (here in Presearch search link)

![Screenshot_20221026-150256](https://user-images.githubusercontent.com/36798218/198034252-b296ded1-822f-4b1b-97c9-e9bddfdfecd5.png)

at no time can I reopen the link in my browser (which is nicely waiting behind ;))

Thanks you

**Comment by TrianguloY** [comment]
Totally agree, I should have made that feature optional from the start. Should be easy, I'll include it in the 2.8.

Just to check something, how are you opening the app with the link from the browser? Sharing it as text is your alternative so I guess you use a different method?

**Comment by Ilithy** [comment]
>Totally agree, I should have made that feature optional from the start. Should be easy, I'll include it in the 2.8.

Thanks a lot, It will be very useful 🥇 ❤️ 

>Just to check something, how are you opening the app with the link from the browser? Sharing it as text is your alternative so I guess you use a different method?

using the android sharing system (share menu)
I show you _(it's more explicit)_

![1](https://user-images.githubusercontent.com/36798218/198064394-dc93352a-16b8-4a71-aaf1-ed06c44db557.png)

![2](https://user-images.githubusercontent.com/36798218/198064414-8d51845d-d809-4f14-9251-f6592294c87e.png)

![3](https://user-images.githubusercontent.com/36798218/198064435-1873b919-1fb1-4a14-9290-b5465ed2e1b7.png)

**Comment by Ilithy** [comment]
Thank you for resolving this so quickly,
It's great
