### ISSUE TITLE
Can´t check URLs from YouTube

### ISSUE THREAD

**Issue by PabloOQ** [TrianguloY/UrlChecker#14]
Prerequisites:
- Default browser app set to none

Steps to reproduce:
1. Open YT app.
2. Go to any video with links in the description. [E. G.](https://www.youtube.com/watch?v=wSy3kAHtmF8)
3. Click any non-YT link.
4. UrlChecker doesn't show up in the "Complete action using" pop-up dialog.

Note that the URL it gives you is a YT redirection, so any links to social media pages won't give you the option to open it in their app, which can be easily solvable with the ClearURLs module.

The only apps I can get to show up are:
- Brave browser.
- DuckDuckGo browser.
- Kiwi browser.
- Firefox browser.
- Firefox focus browser.
- Tor browser.
- URLSanitizer, which is an app to handle URLs too.

Other apps like "Share to clipboard", "UntrackMe" or "Open Link with" do not show up either.

From what I can see it looks like UrlChecker needs to show up as some kind of browser for this to work.

**Comment by TrianguloY** [comment]
Hmm, it does work for me (android 12) but I remember it not working in the past.

Have you tried to set the app to allow opening links as default? I don't know how YouTube detects and shows the list, it's probably using an special intent. I'll try to check.

And thank you for the list of apps that work, that should help me investigate how those apps are configured, hopefully it's just a missing tag on the manifest!

**Comment by PabloOQ** [comment]
> Hmm, it does work for me (android 12) but I remember it not working in the past.

I'm on android 10.

> Have you tried to set the app to allow opening links as default?

Just checked, I can select it as default from settings. Maybe I missed it when I checked yesterday, because I don't remember it being there. Still if there is no default browser it doesn't show up in the dialog. I guess there is no need to not have the app as default browser, as I can easily "share" or "open with" from the menu, coming from multiple segmented apps each one with a specific purpose I really didn't think of it as an option.
