### ISSUE TITLE
New option for modules: Hide module name

### ISSUE THREAD

**Issue by Ilithy** [TrianguloY/UrlChecker#141]
**Describe you'd like**

This option would aim to allow to hide the name of the different modules displayed in the main dialog window of URLCheck

_In my opinion_, this option makes sense in the quantity of modules currently _(but also with those which will come)_ usable in URLCheck; with this option it will leave more space to add new modules, simplify interface, clarify it or simply reduce the size of the URLCheck dialog window...

What do you think about it?

Thank you very much :heart:

**Additional context**

* If we add the space occupied by the titles of each module, this represents a non-negligible part of the useful space of the URLCheck window

* It would be great if this option was configurable separately for each module.

**Comment by Ilithy** [comment]
Thank you very much for the tremendous work you have done on my requests, I thanks you warmly 🫶.

But this request has created a "strange" behavior on URLCheck, as the option is global, if we activate it in order to see the name of the modules (which I think should be the basic case, _for new users_), some module whose name is not basicaly displayed is displayed now (valid for the modules: "Input text" and "Open and share"), this is not a huge problem in itself, but at the same time it does not make this option practical, will it be possible in the future to make this display option customizable for each module independently? _Or any other solution?_

My apologies for the inconvenience 🥺

**Comment by TrianguloY** [comment]
Yes, I'm aware of this limitation.

To be honest I should have never added the module titles, each module should be self-representative and you should be able to know what it does without having the name. That's why I changed the texts (from 'Check' to 'Check status' for example). Still I understand that some users may prefer them and since it's a new design by default, I preferred users to use the old design.

But there was a problem: the edit and open modules didn't have texts, so they were 'strange'. That's why I made them all show the title.

As for why it's a global and not individual option...the reason is UI. I couldn't find a good way to show yet another toggle in each module without cluttering the UI.

I think I'll probably remove the edit/open labels again (the old functionality) while I find a compact and clean way for adding the toggle per-module.

**Comment by Ilithy** [comment]
>To be honest I should have never added the module titles, each module should be self-representative and you should be able to know what it does without having the name. That's why I changed the texts (from 'Check' to 'Check status' for example).

I don't know, I remain in the idea that more options are better than less, and having the possibility of displaying the title of each module is appreciable I find (but not necessarily for all modules), that their uses either explicit or not (this is just my opinion).

>Still I understand that some users may prefer them and since it's a new design by default, I preferred users to use the old design.

Yes I agree with this idea, but if I'm not mistaken, the display of module titles is disabled by default (the option is unchecked)

But there was a problem: the edit and open modules didn't have texts, so they were 'strange'. That's why I made them all show the title.

As for why it's a global and not individual option...the reason is UI. I couldn't find a good way to show yet another toggle in each module without cluttering the UI.

I was thinking of: you click on the option, a floating window is displayed where you select the modules whose name will be displayed.
Simple, efficient and customizable
A bit in his style:

![Screenshot_20221205-113047](https://user-images.githubusercontent.com/36798218/205618494-9f70ba80-f128-4ef3-ae0f-4dbb07bd6359.png)


I think I'll probably remove the edit/open labels again (the old functionality) while I find a compact and clean way for adding the toggle per-module.

Please don't do this, it represents additional work which is not necessarily useful... even counterproductive, some users might prefer to have the title of all the modules...

**Comment by PabloOQ** [comment]
Way cleaner and less cluttered, great new setting.

**Comment by TrianguloY** [comment]
Thanks to both of you! 
I had an idea for the UI, something that may be visually interesting but I have never tried before, will report here first just in case.

(I prefer not to use the checklist dialog because I like to have each module thing on the same place)

**Comment by TrianguloY** [comment]
![image](https://user-images.githubusercontent.com/10616202/205765377-9ed3779b-4ed1-4ace-9a15-f0c06a56ea5d.png)
well, it looks...fine? It's funny because the rounded background looks really good, but the checkboxes are really ugly 😅

**Comment by Ilithy** [comment]
_(my opinion, I'm waiting for @PabloOQ's)_

It seems good to me, I might would have slightly colored the background (for the quibble ^_*).

Yes the checkboxes aren't the most elegant (it's not horrible either), but I guess it's a native android visual element, so you have to deal with it ;-)

Thank you very much for the modification and adaptation work, it's huge, I really appreciate it.

**Comment by Ilithy** [comment]
It's look very clean, I like it too

>Does it look better with switches?

Yes, for my part, I find this really great

**Comment by PabloOQ** [comment]
I personally like the checkboxes, it gives more weight to the module itself and less weight to the options of that module. However I admit I'm usually reluctant to changes. Generally, I think it's preferred to use switches instead, checkboxes aren't that common on phones nowadays, so it's probably better to have the switches.
The border is nice. I haven't updated my app to the lastest commit yet and this is probably nitpicking on my part, but from the image, at first glance it seems the switch to disable modules is too close to the border, and the "show title" switch doesn't have enough space either, one might misstap it when trying to reorder modules.

**Comment by TrianguloY** [comment]
New iteration:
![image](https://user-images.githubusercontent.com/10616202/206047930-aafe7b81-a2c0-46c6-b103-e6f763af5c08.png)

**Comment by Ilithy** [comment]
It looks even better this way 🤩.

_Just a detail, it would be nice for inexperienced users to have a short explanation when long pressing the display/hide module name button._

**Comment by PabloOQ** [comment]
I like it too, the explanation of what the button does could be made on the top.

![image](https://user-images.githubusercontent.com/55493443/206434147-a59cdc46-20e2-4c7f-bb76-bac425eeeee2.png)
