### ISSUE TITLE
(Alpha) Small display problem in the Hosts checker module

### ISSUE THREAD

**Issue by Ilithy** [TrianguloY/UrlChecker#143]
**Describe the bug**

Hi;
Sorry to bother you with this unimportant thing, :-/
but the Hosts module "information" display is not complete,
Thanks.

**To Reproduce**
1. Search for "specific" content (pornography, gambling, etc.)
2. Pass the link to URLCheck
3. See the problem in the host checker dialog box.

**Current behaviour**
The title of the concerned hosts is not displayed in full, only the first word is displayed, the rest is ignored

**Expected behavior**
the full title is displayed

**Screenshots**

**the test for the display of Hosts "gambling", ... in French**
![Screenshot_20221117-120013](https://user-images.githubusercontent.com/36798218/202433499-e5a3e868-c64a-4912-a389-f582d491b209.png)

**the test for the display of Hosts "Porn", "Contenu pour adultes" in French**
![Screenshot_20221117-120142](https://user-images.githubusercontent.com/36798218/202433514-bf3737d1-39f0-49d7-9d5c-a19ac1b62e95.png)

**the Json editor (for comparison):**
![Screenshot_20221117-120207](https://user-images.githubusercontent.com/36798218/202433534-8df18205-451a-464b-895a-f91f0b56f7d9.png)

**System Info:**
 - Device: Pixel 6 pro
 - Android OS version: 13
 - URLCheck version: 2.8 Alpha
 - Browser: Vanadium (chromium)

**Additional context**
This problem is probably also due to the language (French requires more words than English for the same information)

**Comment by TrianguloY** [comment]
Hmm, I remember implementing it to explicitly allow spaces there, may have missed something.
Should be easy to fix, thanks for the report!

**Comment by Ilithy** [comment]
After testing, on my device, none of the values (color, enabled...) are taken into account, but I currently only have one device to test this on, so I'm not sure...

**Comment by TrianguloY** [comment]
Hmm, you are right! I need to check how the data is read, seems to not work properly.

I'll also try to improve the error reporting, but that's a bit more tricky
