### ISSUE TITLE
Import/read URL from clipboard

### ISSUE THREAD

**Issue by slmb3** [TrianguloY/UrlChecker#171]
**Is your feature request related to a problem? Please describe.**
Sometimes I have a URL in my clipboard and can't easily open it in URLCheck without several extra steps (see below).

**Describe the solution you'd like**
A button on the app home page to read from clipboard

**Describe alternatives you've considered**
To open a URL which is currently in clipboard, you can open up a notepad app or something, paste the clipboard there, select the URL, share it to URLCheck, delete the note when done. 

Another alternative that works is to open URLCheck, click the test link that is on the homepage, select all in the edit box, delete the test URL, then paste the clipboard.

These solutions both required several extra steps, having a read clipboard option could reduce it to 2 steps: open URLCheck, click read clipboard. 

A similar app for reference that can read from clipboard is https://github.com/svenjacobs/leon

**Comment by TrianguloY** [comment]
A static shortcut that will open the clipboard text when launched would also be a nice idea, and should be easy to implement.

**Comment by Ilithy** [comment]
It would also be useful to have a method _(or several)_ to quickly access URLCheck (in the case of @bla, so as not to have to multiply the clicks to access the main window of URLCheck):
- the [quick access tile](https://developer.android.com/develop/ui/views/quicksettings-tiles#create-tile) _(which could call URLCheck)_, it remains accessible from anywhere in the interface.
- the [application shortcut](https://developer.android.com/develop/ui/views/launch/shortcuts).
