### ISSUE TITLE
Export/Import app configuration

### ISSUE THREAD

**Issue by Ilithy** [TrianguloY/UrlChecker#175]
**Describe you'd like**
it would be very practical, with the extent of the functionalities, and the quantity of parameters present in URLCheck... to have a function of saving the configuration of the application.

**Additional context**

- It would be nice if the backup could include the log (generated by the logging module).

- It would be perfect if the inclusion of the log in the backup file could be configurable. (for those who do not wish to keep it, those concerned about the size of the backup file, or other reasons)

- it would be great if the backup include advanced editors configuration (for URL Cleaner, Pattern Checker and Hosts labeler module)

Thanks a lot.

**Comment by Ilithy** [comment]
Thank you very much, please take the time

**Comment by TrianguloY** [comment]
This is finally implemented (it only took 1 year!).

I know it took a lot of time, and maybe is not as powerful as expected, but for a first implementation I'm quite happy with it. The update is now live on the playstore as beta, will promote to stable in the following week if nothing bad happens.

I may improve, and add more settings, if people requests it. But for now I'll wait for bug reports (hopefully none!) and tweak as necessary.

I'll close this issue as completed, but feel free to create new ones for improvements or (specially) bugs.
