### ISSUE TITLE
Facebook redirects

### ISSUE THREAD

**Issue by jgmy** [TrianguloY/UrlChecker#180]
### Describe your suggested feature

Open facebook links as you open gmail ones:

Just in case you want to decode facebook links.

Facebook links seem to work this way:
a) first, an encriypted url is opened.
b) then a secondary url is generated, like: https://l.facebook.com/l.php?u=https://www.some-server.org/path/?fbclid=XXXXX&h=XXXX

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Do you mean opening links from the Facebook app? Or what exactly is what you are asking for?

**Comment by TrianguloY** [comment]
I'll close this issue in the following days if no further information is given, I don't know what you want :/
