### ISSUE TITLE
Make the Open & Share feature look like the old bottom sheet in Android <12

### ISSUE THREAD

**Issue by 1fexd** [TrianguloY/UrlChecker#182]
### Describe your suggested feature

It would be very cool if the Open & Share feature would look like the old "Open in App" which Android <12 had:

![thread-133292175-12565258617601683546](https://user-images.githubusercontent.com/58902674/219970305-70425f45-a147-4ff4-86b9-be7b36d5f280.jpg)

It would also be cool if that design used Material3 and Material You.

### Describe alternatives you've considered for your suggested feature

I have used [OpenLinkWith](https://github.com/tasomaniac/OpenLinkWith), which has this exact feature, but does look kind of out-of-place on Android 13

### Other details

Maybe I could try and help implement this feature

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Due to the dialog-like style of the app it would be hard to replicate the same bottom-sheet look, although changing it shouldn't be difficult and maybe worth testing...

As for the list-like feature, that's something already requested and with some tests by pablo: https://github.com/TrianguloY/UrlChecker/issues/47 (and some others, linked there I think).

If you want to try to implement it yourself that'd be wonderful!

**Comment by 1fexd** [comment]
Just wanted to let you know guys: I have implemented the requested functionality in my own app which I will publish on Github/FDroid soon.

**Comment by Ilithy** [comment]
> Just wanted to let you know guys: I have implemented the requested functionality in my own app which I will publish on Github/FDroid soon.

Cool, if I may ask two questions:
Implemented as a replacement for the current behavior or as an option (enableable/disable) of the Open and Share module?
If the answer is yes is it possible to make a PR here with your addition 🤗
Thank you and congratulations for the work done

**Comment by 1fexd** [comment]
> Implemented as a replacement for the current behavior or as an option (enableable/disable) of the Open and Share module?

Implemented as its own standalone app made to better integrate with Android 12+ by using Material3+You as a replacement of [OpenLinkWith](https://github.com/tasomaniac/OpenLinkWith)

**Comment by 1fexd** [comment]
I have uploaded an initial release [here](https://github.com/1fexd/LinkSheet) if you are interested.
