### ISSUE TITLE
Quick/Easy way to load a copied URL to URL Checker

### ISSUE THREAD

**Issue by pressRtowin** [TrianguloY/UrlChecker#187]
### Describe a related problem (optional)

There are cases when you have a URL you copied and it would be nice to be able to quickly load it into URL Checker. Yes, you can always select the URL and share, but if you've already copied it, this requires selecting the text again and going to the Share menu, which takes more time. There are also cases where URLs are added to your clipboard (such as through an action in another website or app, like a copy URL button) and in those cases, it would currently be required to paste it elsewhere first, then re-select it, and finally share it to URL Checker.

### Describe your suggested feature

I see multiple ways this could be done, with the only real pros and cons being dependent on user preference for how they like to interact with their device. These could be seen as distinct features, but as they all functionally accomplish the same thing, I thought it made more sense to group them together here.

1. A widget/shortcut that opens the URL Checker pop-up with the currently copied URL loaded. (This method would be especially useful with a pop-up widget panel such as Samsung's implementation in Good Lock's One Handed Operation +.)
2. A persistent notification that, when tapped, opens the URL Checker pop-up with the currently copied URL loaded.
3. A pop-up dialog that opens when you open the URL Checker application itself with a prompt that asks something along the lines of "Do you wish to load the currently copied URL?" if a URL is detected in the clipboard. Selecting "Yes" would then open the URL Checker pop-up with the currently copied URL loaded.
4. A button in the URL Checker application which opens the URL Checker pop-up with the currently copied URL loaded.

Thoughts? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
https://github.com/TrianguloY/UrlChecker/issues/171

;) 

1) A shortcut was implemented
2) I've never liked these types of notifications. But a quick tile was implemented, which is an alternative.
3) Unfortunately on newer android versions it is not possible to check the clipboard content without that "THE APP READ YOUR CLIPBOARD AND ALL YOUR DATA IS NOW COMPROMISED! WARNING WARNING" toast, so not possible :(
4) Implemented

**Comment by TrianguloY** [comment]
Still not published, it will be on the next version. Should have clarified, sorry!
