### ISSUE TITLE
Packages that support multiple intents are not directly launched by URLCheck

### ISSUE THREAD

**Issue by pressRtowin** [TrianguloY/UrlChecker#195]
### Steps to reproduce

Download any app that provides multiple ways to open a link, such as [AutoShare](https://play.google.com/store/apps/details?id=com.joaomgcd.autoshare&hl=en_US&gl=US). Open a link in URLCheck and check the Open menu. You should see multiple listings of the app. Tap on _any_ of them, as they all lead to the same place. Rather than opening the link using one of the supported methods, you are brought to a system dialog from which you can now choose how the link should be handled:

![Screenshot_20230226_052703_Android System](https://user-images.githubusercontent.com/25999169/221409134-34192555-493f-4cdd-8d46-65ca4da52835.png)

Related to https://github.com/TrianguloY/UrlChecker/issues/183 but a distinct issue.

Originally noted by me [here](https://github.com/TrianguloY/UrlChecker/issues/183#issuecomment-1445336751).

### Expected behavior

Assuming the activities can be correctly distinguished (https://github.com/TrianguloY/UrlChecker/issues/183), selecting one should directly open the link in the intended manner.

### Actual behavior

Users are routed through a secondary system dialog.

### URLCheck version

2.9.1

### Android version

13

### Android Custom/Specific ROM or Device

One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
I think this is solved already.

I'll close the issue, but feel free to reopen if not.
