### ISSUE TITLE
Some applications/intents missing from "Open" list

### ISSUE THREAD

**Issue by pressRtowin** [TrianguloY/UrlChecker#196]
### Steps to reproduce

I'm not sure if this is intended behavior or not, as admittedly, the application that I noticed is missing is coincidentally one of the least consequential applications that could be missing from the list. 😂 Maybe it's being intentionally excluded based on some parameter in the intents that I'm not familiar with. However, if not intentional, I assume one app missing means potentially others could also be unknowingly excluded as well.

The app in question is [Share & Open](https://play.google.com/store/apps/details?id=ru.gelin.android.shareopen&hl=en_AU&gl=US), and if you take a look at its functionality, you'll see why I said it's probably the least consequential app to be excluded from URLCheck's list. That being said, as you can see from the screenshot below, while OpenLinkWith's list _does_ include it, it's missing from URLCheck:

![Screenshot_20230227_035222_Open Link With](https://user-images.githubusercontent.com/25999169/221533773-1eb9c34f-4b30-4212-892b-6daec25b5eca.png)

### Expected behavior

All applications capable of handling a link should appear in URLCheck's list.

### Actual behavior

One application has been observed to be excluded, which, if a bug, could potentially affect some other applications as well.

### URLCheck version

2.9.1

### Android version

Android 13

### Android Custom/Specific ROM or Device

One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
The app asks android for all the apps that can handle the url. Them it removes itself (it has no sense to show itself) and then it removes the origin app (the one that launched the app). This last one can be disabled from the module settings, can you try it first without it just to be sure?

**Comment by TrianguloY** [comment]
Ok thanks, it was just to be sure.
I'll try to install and check it myself, but if someone else has any idea as to why it isn't shown it would be greatly appreciated 😊
