### ISSUE TITLE
2.10 shortcut not available in widget menu after updating

### ISSUE THREAD

**Issue by pressRtowin** [TrianguloY/UrlChecker#197]
### Steps to reproduce

1. Get prompted for 2.10 update.
2. See shortcut in change log. 
3. Update to 2.10.
4. Check widget menu. 
5. Be sad. 😔

### Expected behavior

Not sadness

### Actual behavior

Sadness

### URLCheck version

2.10

### Android version

Android 13

### Android Custom/Specific ROM or Device

One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Do not worry sad user! As the new setting is not a widget but an app shortcut!

How to run it depends on the launcher you are using. On stock android I think it's just by long tapping the app icon, then you can move it to the desktop I think. You should be able to add a direct link too in most cases.

If you still can't, which launcher are you using?

**Comment by TrianguloY** [comment]
Hmm, you are right, the old shortcuts list doesn't show it.
I'll try to add it there too, but it seems that all documentation about it was lost forever (no, seriously, all info I can find is for the new app shortcuts)

**Comment by TrianguloY** [comment]
I think I got it (https://github.com/TrianguloY/UrlChecker/commit/5819216bef24f9b736d16a1377b88ab686fbb97c). Should be available on the next version (which may take a while).
