### ISSUE TITLE
Add to hosted weblate (transferred issue)

### ISSUE THREAD

**Issue by Wjxfi** [TrianguloY/UrlChecker#200]
### Describe what you'd like to see added to the app

add to https://hosted.weblate.org/about/

### Additional information

is a very handy, popular open source project for translating applications.

The free version is only present for open source applications. Your application is perfect for free.
https://hosted.weblate.org/hosting/

https://hosted.weblate.org/about/

https://docs.weblate.org/en/latest/faq.html

'

your app is terribly difficult to translate at this point. I don't want to do it that way. Please consider adding hosted weblate for easy, fast, convenient and simple translation for all languages

**Comment by TrianguloY** [comment]
I'll check it, and if it's both easy for developers and translators I'll enable it. Thanks.

**Comment by TrianguloY** [comment]
I made a quick setup here: https://hosted.weblate.org/projects/urlcheck/

It's still missing some configuration, so please wait and don't create new translations yet until I finish the whole setup. I also need to ask for the libre hosting yet.

You do can check and see if there's something missing or misconfigured, that would be really helpful.

@Ilithy I think you mentioned this service in the past. Sorry for not configuring it sooner (to be honest if I would have knew it was so easy I would have some it sooner, my bad).

**Comment by TrianguloY** [comment]
I'm still awaiting for the 'libre' approval (otherwise the project will be blocked in two days).
I finished configuring it and i think it should be ready to translate, although maybe I missed a couple settings, if so just tell me and I'll try to fix.
It's up to you to translate now or wait until approval.

**Comment by TrianguloY** [comment]
@Wjxfi if you have recently added a translation make sure to fill the new "translators" field (or not, depends if you want to be credited). Originally it was placed as a comment but it's now a dedicated translatable entry to be filled in Weblate.

**Comment by TrianguloY** [comment]
It's now approved, ready to be translated. Closing as completed!
