### ISSUE TITLE
Outdated URL on Open and share module

### ISSUE THREAD

**Issue by PabloOQ** [TrianguloY/UrlChecker#205]
### Steps to reproduce

Setup:

- ClearURLs module enabled
  - Auto-apply enabled
- Open and share module enabled

Steps:
1. Tap on any link that can be cleaned by ClearURLs, the URL should be automatically cleaned.
2. Copy the URL to the clipboard
  - The open with button also shows the compatible apps of the previous URL, to reproduce this a redirection URL needs to be cleaned, YouTube kindly provides those in the description of any video 😉
3. The URL is not actually cleaned

### Expected behavior

The URL should be cleaned.

### Actual behavior

The URL is not Cleaned

### URLCheck version

Commit "split listeners" March 12 [( 3fbb88e5afe9aa7e1f5d2b5508dd5601355ddd1a )](https://github.com/TrianguloY/UrlChecker/commit/3fbb88e5afe9aa7e1f5d2b5508dd5601355ddd1a)

### Android version

5.1.1 API 22

### Android Custom/Specific ROM or Device

Nexus 4

### Other details

I have not made proper testing but it seems like the only affected module is the Open and share, the input module shows the new URL, Queries remover can only remove queries from the new URL and the debug shows the new URL too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PabloOQ** [comment]
I think is not the same thing, but because it originated from the same reason I think I can reuse this issue. Let me know if I should move it to a new issue instead.

Setup:

- History module ON
- ClearURLs module ON
  - Auto-apply ON
 
Steps:
1. Tap on any URL that can be cleared
2. It is automatically cleared
3. Tap on any of the arrows that take you back on the history module, or the clock
4. The URL is not un-cleared

I suspect the URL is reverted and then inmediatly cleared. I don't know if this is intended behaviour but previously it did not work like this, it would go back to the uncleared URL and it would not auto-apply again until the URL was updated.

Which, now that I mention it, should auto-apply options only work **until** the user can interact with the dialog? The way I see it is that if someone reverts the URL it can be because they do not want one or more of the changes the URL has gone through, one of those could be an automatic change.

**Comment by TrianguloY** [comment]
Hmm, it is related, but it's a different issue so yes, open a new issue a link this one, please.
