### ISSUE TITLE
Keep the categories of Uri parts module expanded

### ISSUE THREAD

**Issue by Murilogs1910** [TrianguloY/UrlChecker#235]
### Describe a related problem (optional)

If I want to remove the queries from a Url individually, I have to expand the Queries category, and then press X in each of the queries to remove them. Problem is, whenever I make a change to the Url, the Uri parts module refreshes, and then I have to expand the category again. This was not the behavior of the now deprecated Queries Remover module, it stayed expanded.

### Describe your suggested feature

The categories expanded in the Uri parts module should stay expanded even if there were changes to the Url, just like what happened with the Queries Remover module.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
I switched this to a bug because it should have worked as you describe from the start.
I just... forgot about it >.<

Should probably be easy, a couple booleans to remember the state and adapt.
