### ISSUE TITLE
navigation bar color

### ISSUE THREAD

**Issue by andsofine** [TrianguloY/UrlChecker#24]
apply background color to navigation bar color (for light/dark mode)
![Screenshot_20220628-183941.png](https://user-images.githubusercontent.com/99369164/176222440-b16448dd-b8e2-4cdf-abe3-6e5e1025d8e1.png)

**Comment by TrianguloY** [comment]
The main app screen is usually only seen when installing and/or updating the app, so probably not a big priority. But maybe is just 1 line of code so I'll check.

(1% battery? That's living on the edge!)

**Comment by TrianguloY** [comment]
Ouch.
You meant the black line at the bottom, right? 
To be honest I like the new blue bar, but I'll decide to revert it or not.
