### ISSUE TITLE
Bug in handling query string like ?&

### ISSUE THREAD

**Issue by slmb3** [TrianguloY/UrlChecker#244]
### Steps to reproduce

Not sure if it's technically valid URL or not, but the handling of a string like `foo.bar?&foo=bar` is a bit odd and can be improved.

* If you delete the `foo bar` query, the string returned is `foo.bar?=`. I think `foo.bar?` should be returned.
* I also notice the blank query `?` just shows an empty row. An empty row is better than no row, but I think some hint placeholder text (not sure exactly what it should say) could better indicate that it's an empty query
* Also a string like `foo.bar?&`, when deleting one of the queries it deletes both of them. If you delete 1 I think it should return `foo.bar?`

### Expected behavior

.

### Actual behavior

.

### URLCheck version

2.11

### Android version

10

### Android Custom/Specific ROM or Device

stock

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Hmm, you are right.
For the url handling the app uses the standard android library, and apparently that library allows for empty queries...with some strange behaviours.

Not sure if empty queries are valid or not, but definitely they should be handled better.
