### ISSUE TITLE
Module to display the intent sender app

### ISSUE THREAD

**Issue by edgarogh** [TrianguloY/UrlChecker#248]
### Describe a related problem (optional)

I have a hidden adware on my phone that launches "https:// repekoltorujos (dot) com/?<SUPER_LONG_URI_PARAMETERS>" on Firefox randomly. URLCheck successfully catches the intents, but I would like to know which app is sending them.

### Describe your suggested feature

It would be useful to have access to the package ID of the intent sender, through a module, for instance.

### Describe alternatives you've considered for your suggested feature

I have no other idea of how to find the adware. I don't know about any way to log intents without keeping my phone plugged into a computer with ADB logcat all day long. The URL that's being launched yields no results online so I'm a bit lost.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Exactly as Murilog said.

I'll add the referrer data to the debug module, seems like a useful information. (It can be faked, but still).

But in any case, you should check you phone and analyze it properly to find the source(s) of the malware. I'm not an expert so unfortunately I can't provide a proper solution other than checking the installed list of apps from the android settings, using ADB to analyze the logcat, or any of Murilog's suggestions.

[Note: I edited your post to disable the malware link, just in case]

**Comment by edgarogh** [comment]
Thanks you to both of you for the very helpful comments. I read a bit on `getReferrer` and it is indeed a bit sad that it's spoofable.

I'm currently abroad with only my 10-year old laptop but if I can get Android Studio to run with only 8Gb of RAM, I may try to implement that myself soon.

**Comment by edgarogh** [comment]
Oops sorry, I probably won't be able to do it until Friday, and my PC is indeed not beefy enough anymore for Android Studio. Thank you in advance for your work if you manage to do it 🙂
