### ISSUE TITLE
status code apply automatically

### ISSUE THREAD

**Issue by andsofine** [TrianguloY/UrlChecker#25]
add auto apply check and redirect option

**Comment by TrianguloY** [comment]
I'm not sure if this is a good idea. The redirect module requires fetching the url, that means making a petition with all the consequences (one-click links will behave as if they were clicked, servers can log the petition, etc).
If it were added it would be disabled by default without doubt, but still I think this is dangerous.
An offline redirection (like clearurl does with some) is a better alternative.

Or maybe it can be configured to automatically redirect only urls matching a specific pattern (you could still add .* to redirect all in that case)
