### ISSUE TITLE
Ability to copy URI part

### ISSUE THREAD

**Issue by the-blank-x** [TrianguloY/UrlChecker#250]
### Describe your suggested feature

Either have holding on a URI part copy it to clipboard, or a copy button next to the delete button.

### Describe alternatives you've considered for your suggested feature

Either to tap on the URI part and copy it from the URL box, or to just copy the part from the entire URL. Both are slightly inconvenient though

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
I like the long tap to copy.
Probably not obvious, will try to add it to the module description
