### ISSUE TITLE
auto apply pattern checker rule

### ISSUE THREAD

**Issue by rhjdvsgsgks** [TrianguloY/UrlChecker#257]
### Describe a related problem (optional)

some of rules need to be applied every time when it matched. i dont want click the button to  rule every time

### Describe your suggested feature

add a `auto` field to pattern checker rules. and apply the rule automatically if `auto=true`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PabloOQ** [comment]
That is already possible! Just open the advanced editor and add `"automatic":"true"`, don't forget the comma next to the previous  field.

**Comment by PabloOQ** [comment]
All the possible fields are explained in the advanced editor dialog. Maybe adding a hint about `automatic` and `enabled` in the main description could be a good addition, as those are not "advanced" options.
