### ISSUE TITLE
Allow URLCheck to handle upper-case schemes (eg. "HTTPS://")

### ISSUE THREAD

**Issue by Sophira** [TrianguloY/UrlChecker#258]
### Describe a related problem (optional)

I recently found an issue when using RedReader, one of the third-party Reddit clients for Android which have been whitelisted by Reddit. It turns out that if a post/comment contains a link with an upper-case scheme (for example, [this Reddit comment contains such a link to `HTTPS://join-Lemmy.org`](https://www.reddit.com/r/ActLikeYouBelong/comments/14retl7/ractlikeyoubelong_needs_moderators_and_is/jqsi8bo/)), RedReader does not lower-case the scheme before trying to open it, which results in the intent not being picked up by URLCheck - or, as it happens, by either of the actual browsers on my device. The intent has no receivers. In such a case, RedReader immediately opens the link in its own internal browser.

Now, obviously, this is (arguably) a bug in RedReader and I will be opening an issue there too. However, I believe that **given URLCheck's intended usage** (allowing people to check/clean URLs before opening them), users of URLCheck are likely to find behaviour like this to be startling; not only might the URL be opened without being checked, it might also be in a browser environment they may not wish to use (for example, without ad blockers).

This is obviously not something that URLCheck can *completely* guard against since there's no guarantee that said app will send an intent at all, but where an intent *is* sent it would appear to make sense to attempt to catch it.

### Describe your suggested feature

As schemes are defined as lower-case with a recommendation for programs to treat upper-case as if it was lower-case[1][2], I believe URLCheck should attempt to catch intents where the scheme is in upper-case (or otherwise match it in a case-insensitive manner), and then automatically convert the scheme to lower-case to allow other apps to process the checked URL.

[1] https://www.rfc-editor.org/rfc/rfc1738#section-2.1
[2] https://www.rfc-editor.org/rfc/rfc3986#section-3.1

### Describe alternatives you've considered for your suggested feature

An alternative to automatically changing the scheme to lower-case could be to provide such a mechanism as part of a module such as the URL Cleaner module. However, this seems redundant as there would, in general, be no value to keeping the scheme in upper-case as it may not be matched by other apps.

### Other details

Searching shows that there was a brief discussion in #170 regarding changing case in URLs, specifically in domains. However, **this thread's proposed feature is different** as changing case in a domain will not affect URLCheck's ability to receive the intent in the first place. This feature request is specifically about the fact that URLCheck does not receive an intent where the scheme is in upper-case. (Which is arguably not a bug, given that no other apps do either - hence why I've chosen to make this a feature request instead.)

If this issue is still deemed to be too close to #170, I apologise.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
https://developer.android.com/guide/topics/manifest/data-element#scheme

Android schemes are case sensitive, apparently. Using an uppercase scheme is a bug for the sender app (and you made the correct thing reporting it there), but even in that case, I guess adding an extra intent filter (2 to be precise, HTTP and HTTPS) should be easy to manage. Furthermore, a new default automatic parameter to change the case to lowercase can be added (to also have an automatic sample).

Should be easy...

**Comment by Sophira** [comment]
Makes sense to me. It may also be worth having filters for `Http` and `Https` as well, although I have not (as yet) come across any links using those.
