### ISSUE TITLE
Automatically wipe urls log after some number days or urls 

### ISSUE THREAD

**Issue by 0xedward** [TrianguloY/UrlChecker#263]
### Describe your suggested feature

For the Log module, it would be nice to have a way to specify the following:
1. Automatically remove all urls logged after some user specified timeframe (e.g. remove all urls logged after 7 days using the timestamp on each url to determine whether or not 7 days as past)
2. Specifying a maximum urls in log, then wiping the oldest entry and replacing with a new entry once the limit is hit. (e.g. the limit is set to 20 urls, when the log contains 20 urls, the next url logged will delete the oldest url by timestamp) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Agree.
The log module needs a lot of improvements to be honest. Right now it's just a long text :/
But I'll add a way to limit it in the meantime.
