### ISSUE TITLE
url parts unable to recognize some query

### ISSUE THREAD

**Issue by rhjdvsgsgks** [TrianguloY/UrlChecker#264]
### Steps to reproduce

open https://example.org?amp;a=1&amp;b=1

### Expected behavior

see the query `amp;a` and `amp;b`

### Actual behavior

only domain found

### URLCheck version

2.12

### Android version

android 11

### Android Custom/Specific ROM or Device

lineage

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
It seems the built-in parser fails when there are non-compliant characters in the url, like the ';' here. Apparently it's expected, but not very well documented.
Fortunately there is a [better built-in parser without this issue](https://stackoverflow.com/a/38383741). I'm working on a fix.
