### ISSUE TITLE
Czech Translation proposal (Done 100%)

### ISSUE THREAD

**Issue by Validbit** [TrianguloY/UrlChecker#270]
### Describe a related problem (optional)

I've recently decided to make time to translate your app to my native language since I deem it critical for daily phone usage and thus could help others to start using it too :)

### Describe your suggested feature

Add Czech (finished) translation from Weblate

### Other details

I haven't got problems during translation (from what is seen on phone) but at one point I was uncertain about what 'petition' meant in context (for what terminology/area I should lookup sth about it; if it wasn't a typo/mistranslation from german?) Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Validbit** [comment]
Fixed 1 string (translated explanation instead of locale name)
Updated 7 strings (context correction)

**Comment by TrianguloY** [comment]
Perfect, thanks!
Just let me review it in the following days and then I'll merge it. Don't hesitate to ping me if it takes me more that a week (hopefully not!).

About "petition", what do you mean exactly? Which string are you referring to? Perhaps I can explain where and how it's used.

**Comment by Validbit** [comment]
Currently, there are two strings having that word (weblate):

mStatus_desc
`By pressing the check button, a petition will be made to retrieve and display the site status code. If the result is a redirection, you will be able to view the destination URL. The URL content is obtained (GET), but not evaluated, so redirections based on JavaScript won't be detected.`

mUnshort_desc
`This module will unshort links by sending them to https://unshorten.me/, which evaluates them on their servers and save the redirection for future petitions. Avoid unshortening links with private or sensitive data.
Their api is rate limited to 10 requests per hour for new checks. The module response will show how many petitions you have pending.`

**Comment by TrianguloY** [comment]
Hmm, I guess that provides enough context and are obvious where they are used (in the modules view).

Perhaps that's a mistranslation from Spanish, let see....

A petition (at least on this context) is a request, the act of "asking" the web about that url and obtaining the response.

---

In fact I just checked and yes, petition is not the correct word, request is. I'll change that.
Thanks for telling!

**Comment by TrianguloY** [comment]
Reviewed! I only saw an issue.
The translators field is to write your own name, not the explanation! 😅
https://hosted.weblate.org/translate/urlcheck/app-strings/cs/?checksum=77823bd52e595c34
Can you fix it please?

**Comment by Validbit** [comment]
Done :) thanks for checking
