### ISSUE TITLE
add option to highlight the domain name

### ISSUE THREAD

**Issue by pokegamer5547** [TrianguloY/UrlChecker#285]
### Describe a related problem (optional)

To prevent falling into phishing attacks, reading thats the actual domain name is important. And while you can use uri parts module, you have to manually click on the drop down menu of "domain" to see the domain.
Ofc you can just read the input at top but sometimes the url is made so big by adding like username:password@test.com/test/test/test/test
Ofc android doesnt respect the @ symbol to work in a browser but you get the idea  It's kinda hard to see where exactly is the actual domain part in this. 

### Describe your suggested feature

Add an option to highlight the domain part In the inout field of url checker.

### Describe alternatives you've considered for your suggested feature

Or give a option to auto expand the domain dropdown in uri parts module. Tho it's quite small so it's bit hard for me to read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
This could be a nice addition to https://github.com/TrianguloY/UrlChecker/issues/100, but adding it to the editable input could be also nice if it's easier.
Coloring the other parts of the url could be nice too, but knowing myself I better start with small changes, if possible :/

**Comment by pokegamer5547** [comment]
I think the approach of this app is decent.
![Screenshot_20240501-123915_QR Scanner_1](https://github.com/TrianguloY/UrlChecker/assets/65234485/aef076d3-b0eb-4e3b-8345-ec9101cc4a5d)
It highlights just the domain name by making it bold and making others look normal. 
If you want the url to be bold in your app though, then we can invert it. We can use normal font for domain name and keep using bold for rest.

**Comment by TrianguloY** [comment]
It's the same approach as Discord (and probably more apps) so I agree it should be the first step.

**Comment by TrianguloY** [comment]
This should be already done in the next version (currently in beta and in review for release)

I'm closing as completed, but feel free to reopen if it doesn't work as you expected.
Or maybe even better create a new issue in that case.

**Comment by pokegamer5547** [comment]
> This should be already done in the next version (currently in beta and in review for release)
> 
> I'm closing as completed, but feel free to reopen if it doesn't work as you expected. Or maybe even better create a new issue in that case.

Already tested with beta, it works great as expected thankyou. :)
Also small question i hope you dont mind me asking here, what exactly "replace" option does in hosts configuration? I dont fully understand.

**Comment by TrianguloY** [comment]
> Also small question i hope you dont mind me asking here, what exactly "replace" option does in hosts configuration? I dont fully understand. 

It is explained in the header when editing the json:

```
- replace: if false existing hosts won't be replaced. Note that objects are evaluated from top to bottom. True by default.
```


Since you can provide multiple files, and even some hosts directly, with this property you can choose if it will replace an entry if it exists in a previous file, or it is ignored.
Main use is to replace some host of an external file you don't have access to (that's why it is enabled by default). You will probably never need this unless you are merging a lot of hosts files, but it is there just in case.
