### ISSUE TITLE
+ being replaced with underscore or whitespace

### ISSUE THREAD

**Issue by pokegamer5547** [TrianguloY/UrlChecker#286]
### Steps to reproduce

Enable both status code and uri parts module.
1. Try opening this url via url check.
https://gofund.me/1cba2545
2. Click on check status and click on the redirect link
3. Expand the parameters tab. 

### Expected behavior

It should just show the redirect url as it is.

### Actual behavior

You'll see a empty space between "cp" and and "sharesheet", while parameters tab shows there's supposed to be a underscore. 
if you click copy and paste it in a app like termux, the space will be there. 

Now, If you open the **shorten** link directly in browser (in my case firefox), and when firerox redirects to expanded domain, it'll show + instead of underscore or space. 

### URLCheck version

V2.13

### Android version

android 13

### Android Custom/Specific ROM or Device

lineage os 20

### Other details

![Screenshot_20231118-132601_URLCheck_1](https://github.com/TrianguloY/UrlChecker/assets/65234485/7d188e4c-0f1c-4db1-bcd3-752e8363710f)
![Screenshot_20231118-134427_Firefox Beta](https://github.com/TrianguloY/UrlChecker/assets/65234485/82af4bb7-a551-4f9a-b87e-6934a5cd5118)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Interesting find.
It seems I was incorrectly decoding the location header, which made any '+' be converted to spaces. The uri parts module then was replacing the space (an incorrect parameter) with a '_'.

It's an easy fix, will be fixed in the next version. I just hope that this doesn't breaks other valid redirection urls...

**Comment by soshial** [comment]
Could you please add tests to guarantee that the issue won't regress, @TrianguloY?
