### ISSUE TITLE
Can't open a link from URLChecker into Chrome

### ISSUE THREAD

**Issue by robertoprubio** [TrianguloY/UrlChecker#293]
### Steps to reproduce

Paste a copied link then click to open in Chrome. The link isn't open and UrlChecker displays the main Activity.
No problem if I select other installed browser.
See video

https://github.com/TrianguloY/UrlChecker/assets/31618496/566d6f33-5c87-42f7-be2b-30b2396acce8

### Expected behavior

The link is open in Chrome

### Actual behavior

The link isn't open when I select "open in Chrome"

### URLCheck version

2.13

### Android version

12

### Android Custom/Specific ROM or Device

MIUI 13.0.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Can you check if this workaround works for you? 

https://github.com/TrianguloY/UrlChecker/issues/281#issuecomment-1763818892

**Comment by robertoprubio** [comment]
> Can you check if this workaround works for you?
> 
> [#281 (comment)](https://github.com/TrianguloY/UrlChecker/issues/281#issuecomment-1763818892)

Yes, is working.
The issue also occurs on Cromite and Vanadium, but the workaround solves in both also

**Comment by TrianguloY** [comment]
Perfect, thanks for confirming! 

I'm going to close this as duplicated of #281 then, if you don't mind.
