### ISSUE TITLE
clicking multiple links one after another doesnt update the link in urlchecker

### ISSUE THREAD

**Issue by pokegamer5547** [TrianguloY/UrlChecker#322]
### Steps to reproduce

Luckily I can only reproduce this issue in playstore but its still bit annoying. 

1. Click on any link in playstore
2. Close and click any other link

### Expected behavior

It should use whatever new link you clicked

### Actual behavior

It doesn't update the link and instead uses previous one unless i close and click once again

### URLCheck version

2.13.1

### Android version

android 13

### Android Custom/Specific ROM or Device

lineage os 20

### Other details

https://github.com/TrianguloY/UrlChecker/assets/65234485/8c597412-6e88-4c77-bf69-e0ee952e3f50

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Huh, that's a really strange bug and I can reproduce it! 

However...If I set Firefox a the default browser, it still happens!

Can you also try it? (Choose another browser as the default, then try again).

I'm suspecting the bug is on play store itself...

**Comment by pokegamer5547** [comment]
> Huh, that's a really strange bug and I can reproduce it!
> 
> However...If I set Firefox a the default browser, it still happens!
> 
> Can you also try it? (Choose another browser as the default, then try again).
> 
> I'm suspecting the bug is on play store itself...

Ah it seems you're right. Guess its a bug on playstore app instead. Sry about it i should have done more lookup, closing the issue.
