### ISSUE TITLE
Buy a coffee app typos

### ISSUE THREAD

**Issue by gnevan** [TrianguloY/UrlChecker#336]
### Steps to reproduce

No repository so I am writing here... Typos in a message "You thing ...".

### Expected behavior

"You think simply pressing a button will get rid of me?"

### Actual behavior

"You thin**g** simply pressing a button will get rid**e** of me?"

### URLCheck version

n/a

### Android version

Android 10

### Android Custom/Specific ROM or Device

-

### Other details

Please delete this issue after it is read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Oh, thanks! 
I guess an email could have work too, but this is fine.

I'm going to close this, but feel free to add more typos you find here (although I'll review all texts myself, I'm a bit ashamed but my excuse is that I made that app when I was less proficient with English!)

**Comment by gnevan** [comment]
Absolutely not a problem, especially for such a complicated logic app! Thank you.
