### ISSUE TITLE
Url scanner toggle not working 

### ISSUE THREAD

**Issue by st3v-1** [TrianguloY/UrlChecker#352]
### Steps to reproduce

In module section url scanner toggle not working. It says "can't enable module missing api"

![IMG_20240430_225001](https://github.com/TrianguloY/UrlChecker/assets/132986620/46a1dbf6-7375-4734-bed0-667bb0b0bd66)

### Expected behavior

Url scanner Toggle turned to be on.

### Actual behavior

Url toggle not turned on

### URLCheck version

V2.15

### Android version

Android 9

### Android Custom/Specific ROM or Device

Color os 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
You need to open the module settings (press the `> Url Scanner` element) and fill the api key textbox with your own api key. You can get one by registering for a free Virus Total account in the description [link](https://www.virustotal.com/gui/join-us). After the key is inserted, you will be able to toggle and use the module.
