### ISSUE TITLE
All modules get disabled/enabled by themselves

### ISSUE THREAD

**Issue by KnockoffFeline** [TrianguloY/UrlChecker#362]
Steps to reproduce:
1. Open URLCheck from your home screen
2. Open the "Modules" screen
3. Find a way to unload the app (frex, open other apps and interact with them as much as possible)
4. Open URLCheck again.
5. See that all modules get disabled by themselves. On rare occasions, they all try to enable themselves.

**Comment by TrianguloY** [comment]
I have a suspicion about this, and I think I managed to trigger this on the emulator, but I though it was due to the emulator itself.
Thanks for the report!
