### ISSUE TITLE
Queries remover crashes on empty query

### ISSUE THREAD

**Issue by PabloOQ** [TrianguloY/UrlChecker#365]
### Steps to reproduce

1. Enable queries remover
2. Open an url with an empty query like https://example.com?=

### Other details

Throws an IndexOutOfBounds on method [getQueryName](https://github.com/TrianguloY/UrlChecker/blob/master/app/src/main/java/com/trianguloy/urlchecker/modules/list/RemoveQueriesModule.java#L190).

I don't think I will look further into it as I rather spent the time on the incognito issue, but I wanted to log the issue.
Also the module is deprecated, so maybe the fix is just not planned?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
For a moment I though it was a crash on the new module 😅
I'll take a look. It should probably be easy to fix, although if for some reason it isn't, I'll consider removing the module.
👍
