### ISSUE TITLE
Aggressive word breaks in ui

### ISSUE THREAD

**Issue by KorigamiK** [TrianguloY/UrlChecker#372]
### Steps to reproduce

Open any url with firefox as default 

### Expected behavior

Text should not break

### Actual behavior

![Screenshot_2024-07-29-15-32-01-63_21561dfd7cdb810023cdb17e8b11e256](https://github.com/user-attachments/assets/8b830c57-b80b-42ec-9209-16d59553c249)

### URLCheck version

2.16

### Android version

Android 12

### Android Custom/Specific ROM or Device

Stock

### Other details

A feature to enable/disable the browser icon in the popup would allow more space for the text

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
That's a small screen.

But there is already a setting to disable the icon:

Open the app, modules, open & share, icon size = None (the setting is the last one for that module).

Does it fixes the issue?

**Comment by KorigamiK** [comment]
Great! I didn't know about that
