### ISSUE TITLE
Unexpected Toast Notification 

### ISSUE THREAD

**Issue by skal-dB** [TrianguloY/UrlChecker#379]
### Steps to reproduce

I have these toast appearing from time to time. Not sure what triggers it. 
![Screenshot_20240917-002030__01](https://github.com/user-attachments/assets/d45bbcb9-6f07-4c76-87a3-6c9d02486e5d)
![Screenshot_20240917-001236](https://github.com/user-attachments/assets/78927670-3e0e-4a7b-82ff-653990627e66)

### Expected behavior

Not having these message.  

### Actual behavior

Displays 2 toasts notification I don't understand

### URLCheck version

2.16

### Android version

Android 11

### Android Custom/Specific ROM or Device

OnePlus 6T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PabloOQ** [comment]
This is from the debug/marker module.
Disable the toggle "Show debug messages from the custom tabs service" and it should be gone.
