### ISSUE TITLE
Icons in light mode

### ISSUE THREAD

**Issue by PabloOQ** [TrianguloY/UrlChecker#38]
Already mentioned in #23

I can't see the custom tabs icon at all. Also the other icons do not look good either. I think the best would be to have these icons be filled with black on the inside.
![image](https://user-images.githubusercontent.com/55493443/182895082-48c4506e-4dc7-46c5-9f2f-8bce35eddb84.png)

**Comment by TrianguloY** [comment]
Known issue, already working on it.
Fixing it for android 5+ is easy. And for android <5 is relatively easy too. But unfortunately mixing both fails and I'm still trying to check if it works. The changes are on the main branch if you want to test them.

**Comment by TrianguloY** [comment]
Btw, this is how I want the next version to be: https://github.com/TrianguloY/UrlChecker/discussions/34#discussioncomment-3269081

**Comment by PabloOQ** [comment]
> Btw, this is how I want the next version to be: [#34 (comment)](https://github.com/TrianguloY/UrlChecker/discussions/34#discussioncomment-3269081)

And how would changing the app to open the url with work? Long tap? I myself, do not change the app I open urls that much, so to me the change gives more free space at the cost of sometimes, very rarely, spending a tiny bit of time holding the button, instead of taping the arrow. So a great change overall, the GUI is cleaner. I also like the roundness. 

> The changes are on the main branch if you want to test them.

Found this GUI bug while testing it, in the open & share module, only happens with Brave. The 'o' in 'open' is half way outside the button.

![image](https://user-images.githubusercontent.com/55493443/183127162-f01ed077-f1d3-4a01-8a06-b45a03978af7.png)

**Comment by TrianguloY** [comment]
Long tap doesn't do anything, the arrow is shown when there are more than 2 options, like it does now. In fact only the styles changed, the functionality is the same.

There are issues with paddings, yes. The arrow and the text are not centered either. It's still a work in progress.
