### ISSUE TITLE
Default state for "Toggle custom tabs" and "Toggle incognito mode"

### ISSUE THREAD

**Issue by jazz-it** [TrianguloY/UrlChecker#385]
### Describe a related problem (optional)

Currently the default state for those two buttons is hardcoded. My preferred states are the opposite of those defaults and everytime I want to open a link, I need to press 3 buttons, which is quite annoying. I should be able to choose my defaults, so pressing not even a single button would be necessary.

### Describe your suggested feature

There should be a setting within the app to set the defaults for those two toggle buttons, so the app can remember those preferences. Additionally, the app should offer a setting to open the links automatically in the preferred browser.

### Describe alternatives you've considered for your suggested feature

Optionally, perhaps this could be done through app's modules, or a checkbox "Remember these preferences". Ideally, after I choose my preferred settings, every time I press the URL that supposed to be opened by URLcheck, there should be an option to open the URL automatically with the preferred settings.

### Other details

Please let me know if this feature is already feasible somehow.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
It's...already there 🤔

Open the app (from your launcher), press "modules", expand "open and share" and if you scroll a bit you'll see the options for both custom tabs and incognito mode.

You can choose between several different states. Always on, default off, automatic...

Does it not work for you?

**Comment by jazz-it** [comment]
I just figured out my both preferred settings should be "Enabled by default" within the module and now it works as as you described above.

I also proposed a setting to open the URL automatically, without even pressing that single button. I've noticed the "Close dialogue after opening" setting, but is there a way to skip showing the dialogue altogether and opening the URL automatically by applying those defaults?

**Comment by TrianguloY** [comment]
> I just figured out my both preferred settings should be "Enabled by default" within the module and now it works as as you described above.

Glad it works.

> I also proposed a setting to open the URL automatically, without even pressing that single button. I've noticed the "Close dialogue after opening" setting, but is there a way to skip showing the dialogue altogether and opening the URL automatically by applying those defaults?

Not yet, but may be soon: https://github.com/TrianguloY/UrlChecker/discussions/383
