### ISSUE TITLE
app dissappears from recent apps while still running in background when opening a url from within the app

### ISSUE THREAD

**Issue by pokegamer5547** [TrianguloY/UrlChecker#387]
### Steps to reproduce

1. Open any url within app from log history or about section

### Expected behavior

The app should either keep current process as seperate window or simply close current process entirely

### Actual behavior

The urlchecker app after opening the link dissapears from recent apps. But if you click on app icon on launcher you'll realize that it's still running in background as it opens the same screen where you left off (unless you force stop it)

### URLCheck version

2.17

### Android version

Android 14

### Android Custom/Specific ROM or Device

Lineage os 21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
This is sort of a know issue, but each time I try to configure the "show/hide on recents" behavior it fixes some things but breaks others. Theoretically it should be possible to configure the main dialog as an independent popup-only thing, while keeping the rest of theconfiguration activities like a normal app...but I don't really know how to (even though it seems like a really easy thing...).

I'll take another look, but if someone knows better, please let me know!

**Comment by ccrowles** [comment]
This is an issue again, started happening recently (I think about a month or so ago? Not really sure). I'm running version 3.5. My enabled modules are: input text, history, unshortener, status code, URL scanner, URL cleaner, pattern checker, hosts labeler, open and share.

Running Android 14, on a ZenFone 9.

https://github.com/user-attachments/assets/0d3a4461-9e57-4a8b-9cae-97e411e2c61d
