### ISSUE TITLE
total URL conversion

### ISSUE THREAD

**Issue by ildar** [TrianguloY/UrlChecker#389]
### Describe your suggested feature

I'd like to see URLChecker converting (roughly) `https://gitlab.something.com` to `labcoat://gitlab.something.com`. This is what e.g. https://gitlab.com/nomadlabs/deeplinks/ awkwardly does.

### Describe alternatives you've considered for your suggested feature

I guess if [Regex](https://github.com/TrianguloY/UrlChecker/issues/170) worked, that would kinda solve the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
That regex issue you link is for allowing changing the letters case in the pattern checker module.

But your request doesn't seems to require that.

A configuration like this should work:

```json
  "Test": {
    "regex": "^https?(:\/\/(git\\.socketmobile\\.com|salsa\\.debian\\.org|gitlab\\.freedesktop\\.org|gitlab\\.gnome\\.org|git\\.gnu\\.io)/.*$)",
    "replacement": "labcoat$1"
  }
```

(You could also use a more generic "^https?(://gitlab\\.[^.]*\\.com/.*$)" if you prefer)

**Comment by ildar** [comment]
yes, found that `Template checker` module after filing the issue. Will try
it.
Sorry for the noise.

**Comment by TrianguloY** [comment]
Don't worry.
I'll close this issue, since the feature you request is available. But feel free to ask for more help here if needed.

**Comment by AdityaMH** [comment]
@TrianguloY Give me another example replacement like from ˋhttps://media.discordapp.net/attachments/653653538164965416/1308051369285914654/IMG_20241118_155210.jpg?ex=67407dc4&is=673f2c44&hm=836ce60cb76cf8e5afe8fc0ac1bc01cf3a596bf6e9bebfd2c8ca4235e61553f5&ˋ to ˋhttps://cdn.discordapp.com/attachments/653653538164965416/1308051369285914654/IMG_20241118_155210.jpgˋ ?

or ˋhttps://music.youtube.com/watch?v=123ˋ to https://youtu.be/123`

**Comment by AdityaMH** [comment]
Thanks!! They all worked except youtube still have useless parameter.

**Comment by TrianguloY** [comment]
> Thanks!! They all worked except youtube still have useless parameter.

Ah, wait, there was an extra dot, I fixed it in the message above
