### ISSUE TITLE
Next link not clickable anymore

### ISSUE THREAD

**Issue by Entwineo** [TrianguloY/UrlChecker#394]
### Steps to reproduce

After clicking check status results show next redirection link, which was clickable in previous version. 
![Screenshot_2024-11-07-18-14-09-846_com trianguloy urlchecker-edit](https://github.com/user-attachments/assets/6380fd4e-1a62-4dd1-869d-fcc0f40fa816)

### Expected behavior

It should open/paste clicked link

### Actual behavior

Currently it didn't do anything.

### URLCheck version

3.0

### Android version

14

### Android Custom/Specific ROM or Device

Stock Xiaomi HyperOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Arg, I can confirm the issue. It also happens in the unshorter module, hopefully just a missconfiguration.

I'll need to fix this this before the 3.0 release.

Thank you for the report!
