### ISSUE TITLE
Option for app to close upon passing of URL via open or share buttons

### ISSUE THREAD

**Issue by ig9000** [TrianguloY/UrlChecker#42]
For at least some use cases, there's no further need for a URLChecker instance after the URL has been processed and passed along to another app using the browser or share buttons. This could be a simple boolean setting, or it could even be conditional based on a regexp or something. It might make sense for "open" and "share" to be individually configured in this regard, especially if they are split into separate modules.

**Comment by ig9000** [comment]
Implementation-wise, maybe it would make sense to make this a checkbox shown in the modules for open/share, so that it could be easily disabled for the (odd?) cases where keeping the app open is desired.

**Comment by TrianguloY** [comment]
The current behavior is to keep the app open, or to be precise not to close it. [There is no finish() call when you press the open button](https://github.com/TrianguloY/UrlChecker/blob/master/app/src/main/java/com/trianguloy/urlchecker/modules/list/OpenModule.java#L242).
However this app is configured to not appear on recents so when you open a different app there is no way to go back and it appears as closed even though it's not (well, android probably closes it, but not the app itself)

**Comment by ig9000** [comment]
Yes, this might make more sense for "share" than for opening in a browser. The share functionality is sometimes used to hand the URL to apps which function in the background (downloader, bookmarking, etc). Those are the cases where I'm then left with URLChecker interface still in front of me, but no longer needed. It's not a big deal, but it would streamline things a little.

Example use case is being sent a URL via SMS while using a laptop or desktop device, and you want to quickly and easily pass that URL to one of the various methods for making it available on that device, while continuing to interact with the SMS app on the phone.
