### ISSUE TITLE
Add more clearurl parameters for Tiktok links

### ISSUE THREAD

**Issue by flexagoon** [TrianguloY/UrlChecker#5]
I use this app to open tiktok links because they are shortened and when you go to them they expand to a url with a lot of tracking parameters. However, this app does not detect some tiktok tracking params.

Here are the parameters which are not detected:
- checksum
- sec_user_id
- share_app_id
- share_item_id
- share_link_id
- tt_from

**Comment by TrianguloY** [comment]
Hmm. The app uses the [ClearUrls dataset](https://github.com/ClearURLs/Addon/) which doesn't appear to have those.

According to its Contribute readme:
> Note: If you have any suggestions or complaints regarding the rules, please [create an issue in this repo](https://gitlab.com/anti-tracking/ClearURLs/rules/-/issues/new) or email us rules.support (at) clearurls.xyz (this mail will automatically create a new issue in this repo).

**Comment by TrianguloY** [comment]
With the new update you can now add your own rules, so this should be possible. In any case I think the good solution is to let the ClearUrls devs know about this and let them implement it.

I'm closing this issue as I think this is already solved.
