### ISSUE TITLE
Logo is not appearing in the launcher icon

### ISSUE THREAD

**Issue by krishnapandey24** [TrianguloY/UrlChecker#53]

**Comment by TrianguloY** [comment]
Which device, android and app version?
This bug was present in a previous version but I though I had already fixed it.

**Comment by Ilithy** [comment]
That's a concise description ^^

on my pixel 6 (android 12L) the icon is correctly displayed by the system, and by the (tired) launcher of android 12 aosp. _(my main launcher does not use icons)_

![Screenshot_20220819-153519](https://user-images.githubusercontent.com/36798218/185632662-39dbdf1e-8fa8-48b8-9b89-e5aff3aa28a4.png)

![Screenshot_20220819-153817](https://user-images.githubusercontent.com/36798218/185632801-e3e2c7cb-92cd-4e07-b1b8-29f7a1c5d8aa.png)

**Comment by krishnapandey24** [comment]
> Which device, android and app version?
> This bug was present in a previous version but I though I had already fixed it.

I am using Realme 8 pro and the app version is 2.4
![IMG_20220819_225933.jpg](https://user-images.githubusercontent.com/80609574/185675137-77843add-1b79-4d64-bd20-ceb795bc4256.jpg)

**Comment by Ilithy** [comment]
@krishnapandey24 Please could you test with the version 2.6 present on the Play Store or the version 2.5 present on F-droid? This would surely solve your problem.

**Comment by krishnapandey24** [comment]
> @krishnapandey24 Please could you test with the version 2.6 present on the Play Store or the version 2.5 present on F-droid? This would surely solve your problem.

It works now! I uninstalled the app and installed it again from play store.

**Comment by Ilithy** [comment]
Glad to hear it.

**Comment by TrianguloY** [comment]
Glad it's solved. Version 2.5 does have a fix for icons not appearing, and didn't remember it affected the launcher too.
Thanks Ilithy for the help! I'm closing this as solved.
