### ISSUE TITLE
Add vertical padding to the open button

### ISSUE THREAD

**Issue by TrianguloY** [TrianguloY/UrlChecker#57]
See ![](https://raw.githubusercontent.com/TrianguloY/UrlChecker/66068a496744a99b2c761423b234d491ef84b47d/app/src/main/play/listings/uk-UA/graphics/phone-screenshots/3-dialog.png)

**Comment by Ilithy** [comment]
I can confirm that this is resolved: 

![3-dialog (1)](https://user-images.githubusercontent.com/36798218/185864126-91f408e8-cffc-4b47-b024-c8fcfbb3830e.png)

Well done, thanks

**Comment by Ilithy** [comment]
_(Sorry)_ I have found a another things on hebrew version:

![IMG_20220822_115859](https://user-images.githubusercontent.com/36798218/185896625-e4bc2861-298e-40d9-9fa8-5d9afa03d674.jpg)

_I am just forwarding you the information, it is not critical_

**Comment by TrianguloY** [comment]
hey, that's a bug you found, don't be shy!
could you create an issue with it?

**Comment by Ilithy** [comment]
> hey, that's a bug you found, don't be shy!
> could you create a new issue with it?

Thanks, that's okay.
I opened a  issue.
