### ISSUE TITLE
(Useless) notification in android 13

### ISSUE THREAD

**Issue by Ilithy** [TrianguloY/UrlChecker#74]
Hi;
It turns out that the copy notifications (after a long press on the "share" button) are duplicated (Android 13 aka Tiramisu has its own notification system), and are not really necessary anymore (only under Android Tiramisu).

I attach a screenshot:
![Screenshot_20220826-072913](https://user-images.githubusercontent.com/36798218/186830758-3f6ca6dd-6429-4654-a997-25ba5ed1a461.png)

It's not really a bug, rather a _(slightly)_ annoying element _(it's a bit inelegant, without in any way preventing the use of the feature.)_

There is this which explains how to display these notifications only under versions older than Android 13:
https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#duplicate-notifications

~~(As a total aside, is it possible in the future to add an option in Url Checker in order to hide the data copied in the clipboard?) as proposed by this:
https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent~~

Thanks

**Comment by TrianguloY** [comment]
The sensitive flag will probably require a different button or something, and for only one version I don't think it's really necessary (I accept suggestions though)

Removing the toast should be a two lines change, if no one want to do it I'll probably implement it tomorrow.

**Comment by Ilithy** [comment]
> The sensitive flag will probably require a different button or something

I don't know, I think it wouldn't be too complicated to add (hope, hope) and I would hope that it would be implementable, because it clearly increases privacy when using UrlCheck (it may not matter as much as I imagine)

>and for only one version I don't think it's really necessary (I accept suggestions though)

Only one version? Why only one? 

> Removing the toast should be a two lines change, if no one want to do it I'll probably implement it tomorrow.

 Normally yes, but I dare not be categorical, because I tried and did not succeed, (I have no doubt that you could succeed, but I would have liked to do it), it is not hurry, take the time you need, thank you very much.

**Comment by TrianguloY** [comment]
That sensitive flag https://developer.android.com/reference/android/content/ClipDescription#EXTRA_IS_SENSITIVE is for android 13 only (api 33) thus only 1 version: android 13 (it will increase in the future with newer versions...unless they remove or change it again).

It can be added, sure, but there are other more important features. 
I can make it the default though...

**Comment by Ilithy** [comment]
I'm sorry, I was referring to something else, I must be mistaken and misunderstood

```
// When your app targets API level 33 or higher
clipData.apply {
    description.extras = PersistableBundle().apply {
        putBoolean(ClipDescription.EXTRA_IS_SENSITIVE, true)
    }
}

// If your app targets a lower API level
clipData.apply {
    description.extras = PersistableBundle().apply {
        putBoolean("android.content.extra.IS_SENSITIVE", true)
    }
}

```

>It can be added, sure, but there are other more important features.
I can make it the default though...

I don't know if it's the best or not, moreover if only the devices under tiramisu take advantage of it, it doesn't matter at the moment, like the "worry" of the double copy notifications, it doesn't block the use of the app and only impacts a very small number of users, so it can be largely postponed to later.

**Comment by TrianguloY** [comment]
No, no, I was referring to the fact that that new feature (showing the copied text as private) is only used in Android 13. That alternate code is just in case you are not using the Android 13 code, but for some reason you want to still allow it. Android 12 and below will see that extra flag and simply ignore it either way.

Which means that either I always set it, so in android 13 all copied links are considered private (which personally don't like) or think of a way to allow to choose "copy as private" and "copy normal". This second option is the one that is tricky (if it requires an extra button I need to disable it for all versions except 13).

In the future when more devices use Android 13 it can be revisited again, but right now it's just something with very low priority.

**Comment by Ilithy** [comment]
>No, no, I was referring to the fact that that new feature (showing the copied text as private) is only used in Android 13. That alternate code is just in case you are not using the Android 13 code, but for some reason you want to still allow it. Android 12 and below will see that extra flag and simply ignore it either way.

All right! So I had misunderstood, thanks for the clarification.

> Which means that either I always set it, so in android 13 all copied links are considered private (which personally don't like) or think of a way to allow to choose "copy as private" and "copy normal". This second option is the one that is tricky (if it requires an extra button I need to disable it for all versions except 13).

Yes, that would be the best, but it's a lot of work. _(for actually almost no benefit for the end user)_. Again, thank you for your explanation.

> In the future when more devices use Android 13 it can be revisited again, but right now it's just something with very low priority.

It's clear, I totally agree.

Thanks for all
