### ISSUE TITLE
Detail in URL scanner module

### ISSUE THREAD

**Issue by Ilithy** [TrianguloY/UrlChecker#86]
_Note that this is without priority, it "affects" a really minor detail_

- In the report of the url scanner there is nothing between the date and the time, it would be more readable if there was an element between the two,
Like for example:
   - en: `2022-12-31 at 06:22:01`
   - es: `2022-12-31 a las 06:22:01`  
Etc..

If it were possible to change this, it would be more pleasant, if not, that's fine, thank you.

**Screenshot**

![IMG_20220901_205409](https://user-images.githubusercontent.com/36798218/187991329-03c8b209-7ccc-4b08-bdd1-c53b52b889b3.jpg)

**Comment by TrianguloY** [comment]
The date is directly extracted from the [api response](https://developers.virustotal.com/v2.0/reference/url-report) and unfortunately the documentation doesn't specify the exact format so parsing can fail in some cases with unexpected outputs.

**However**

Apparently there is now a [newer api version](https://developers.virustotal.com/reference/url-object) that does return the date as utc integer timestamp.

I'll close this bug as don't fix, but the update to the v3 api (if it is made) will fix this.

**Comment by Ilithy** [comment]
Perfect, thanks.
