### ISSUE TITLE
New module: query parameter manager

### ISSUE THREAD

**Issue by slmb3** [TrianguloY/UrlChecker#9]
Thank you for making and sharing this app, it's really nice.

My suggestion is a module that parses all the query parameters, displays them as a scrollable list, and allows you to edit or delete any query parameter from the URL from the list (by tapping or swiping or something). A delete all parameters option would be useful as well. A bonus to this feature could include ability insert new parameters as well.

Example: https://example.com/?a=1&b=2 would show a list:

* a=1
* b=2

Deleting `a=1` would transform the url to https://example.com/?b=2

**Comment by slmb3** [comment]
@PabloOQ thank you! And @TrianguloY thank you for reviewing and merging! 

The feature looks great. Multiple key handling is intuitive, I like it.

What do you think about including the parameter value in the list as well?

**Comment by TrianguloY** [comment]
Totally agree. I even though about displaying it decoded, and even letting it be copied or even setting it as the new url. (But didn't had time to implement it)

**Comment by slmb3** [comment]
The new update looks nice! 
One more potential improvement I see is to not make the param key in all caps (foo=bar shows `REMOVE FOO bar`)

**Comment by Ilithy** [comment]
> The new update looks nice! One more potential improvement I see is to not make the param key in all caps (foo=bar shows `REMOVE FOO bar`)


In the last version, the keys are well displayed in lower case, here _(version 2.6-alpha)_

![Screenshot_20220827-124622](https://user-images.githubusercontent.com/36798218/187026849-c785277b-f2cd-4d80-a813-1890773aa627.png)

**Comment by TrianguloY** [comment]
The upper case buttons is a standard android feature that is enabled in most versions, but not all.

In think I can disable it.

**Comment by slmb3** [comment]
Odd and interesting. Thanks!
