### ISSUE TITLE
it does not open any urls

### ISSUE THREAD

**Issue by 100doses** [TrianguloY/UrlChecker#91]
**Describe the bug**
It does not open any urls

**To Reproduce**
1. Click on any urls in any apps and bam.

**Current behaviour**
All urls are openned on the stock Android apps

**Expected behavior**
Open urls in UrlChecker

**Screenshots**
Can't screenshot a click on a link

**System Info:**
 - Device: Oppo A74 4G
 - Android OS version: 12
 - URLCheck version: 2.6
 - Browser: Brave, Firefox, YouTube, Google, etc...

**Additional context**
Nothing more

**Comment by TrianguloY** [comment]
Does it work if you click the link on the app main screen? That's hardcoded to open the app, if it does not then this is a bigger problem.

If it does open, which is the most probable outcome, then you probably need to manually configure the app as the main browser. For android 12 you should go to:
- Android settings, apps, default apps, browser -> make sure urlchecker is chosen

**Comment by Ilithy** [comment]
I just tested version 2.6 on an oppo a74 4G (updated), and I don't have this problem.

However, as the developer says, you have to configure it as a default browser so that it opens links automatically, otherwise, long press on a link --> share --> URLCheck work fine

**Comment by 100doses** [comment]
> Does it work if you click the link on the app main screen? That's hardcoded to open the app, if it does not then this is a bigger problem.
> 
> If it does open, which is the most probable outcome, then you probably need to manually configure the app as the main browser. For android 12 you should go to:
> 
> * Android settings, apps, default apps, browser -> make sure urlchecker is chosen

I can't configure it to open links by default.
![ss](https://user-images.githubusercontent.com/95159500/189116944-c288fdb5-ce3b-4550-8e68-7803bb5bb953.jpg)




> I just tested version 2.6 on an oppo a74 4G (updated), and I don't have this problem.
> 
> However, as the developer says, you have to configure it as a default browser so that it opens links automatically, otherwise, long press on a link --> share --> URLCheck work fine

Long pressing on in-app URLs does nothing. :/

**Comment by Ilithy** [comment]
@100doses ist not the good place for this setting, to select Url Checker as the default browser, here is the procedure:
go to settings.

**Go to the Application tab**
![threema-20220908-210256751](https://user-images.githubusercontent.com/36798218/189206523-5c11158b-aeb1-452b-a85a-67f06d8c1fa2.jpg)


**then default apps**
![threema-20220908-210256518](https://user-images.githubusercontent.com/36798218/189206544-0d0c6136-0dd9-46b3-89bd-512d89fae58a.jpg)


**then Default browser**
![threema-20220908-210256286](https://user-images.githubusercontent.com/36798218/189206581-2f27db16-f4ef-4334-8856-cbf91c3a66da.jpg)



for the long press, I just tested (version 2.7 install from the Play Store) it works perfectly:

![IMG_20220908_210318_01](https://user-images.githubusercontent.com/36798218/189206752-bfdb0d10-aa74-436a-a414-779b6a52369f.jpg)

**Comment by Ilithy** [comment]
@TrianguloY There is an [application](https://github.com/k3b/intent-intercept) that intercepts all "intents", wherever they come from, using that (I know, that's a rude way of speaking for such code adaptation work) would allow (I think :3) it has significantly improved URLCheck's ability to "capture" links (regardless of their origin) and to do its job (know where it leads, if they are sure, later possibly redirect users to an app alternatives, etc.).
I don't know if it's useful (and usable), so I'll let you know...

**Comment by TrianguloY** [comment]
I was aware of the original (discontinued) app, happy to hear there is an updated version. I'll keep it in mind if I need to check how to open more special links. Thanks!

**Comment by 100doses** [comment]
> @100doses It's not the good place for this setting, to select Url Checker as the default browser, here is the procedure: go to settings.
> 
> **Go to the Application tab** ![threema-20220908-210256751](https://user-images.githubusercontent.com/36798218/189206523-5c11158b-aeb1-452b-a85a-67f06d8c1fa2.jpg)
> 
> **then default apps** ![threema-20220908-210256518](https://user-images.githubusercontent.com/36798218/189206544-0d0c6136-0dd9-46b3-89bd-512d89fae58a.jpg)
> 
> **then Default browser** ![threema-20220908-210256286](https://user-images.githubusercontent.com/36798218/189206581-2f27db16-f4ef-4334-8856-cbf91c3a66da.jpg)
> 
> for the long press, I just tested (version 2.7 install from the Play Store) it works perfectly:
> 
> ![IMG_20220908_210318_01](https://user-images.githubusercontent.com/36798218/189206752-bfdb0d10-aa74-436a-a414-779b6a52369f.jpg)

Sorry, i did a pause from Internet and i didn't seen you answered me.
It works now, you're a legend, thanks. ^^

**Comment by TrianguloY** [comment]
Happy to know it's fixed now. And thanks @Ilithy for the detailed steps with screenshots! 

Closed as solved

**Comment by Ilithy** [comment]
@100doses My pleasure, as long as it works, I'm happy, thanks you for the feedback <3

@TrianguloY I think the subject can be closed
