### ISSUE TITLE
Allow disabling all modules

### ISSUE THREAD

**Issue by TrianguloY** [TrianguloY/UrlChecker#99]
The input text and open&share modules can't be disabled currently. I think I made them that way because they provide the minimum functionality, but I don't think there is necessary code-wise. Maybe some users only want to edit the url, or maybe only check and open.

What will happen if the users disables all modules? I have some ideas...

**Comment by Ilithy** [comment]
It's a good idea, not necessarily really useful, but not being able to deactivate them is a bit frustrating

>What will happen if the users disables all modules? I have some ideas...

:eyes:
